### ISSUE TITLE
revolution/mini compatibility

### ISSUE THREAD

**Issue by rhaamo** [tuxtof/freebox-monitoring#1]
hello,

is a mini/revolution script short-planed ?

I'm currently replacing my old munin and interested to have this plugin.

I may be able to do something if you want.

**Comment by tuxtof** [comment]
Hello Marc,

I don't have this kind of hardware so it's a little more complicated to do it.
But  i have a colleague who start building this same kind of stuff for his Freebox Revolution with fiber connection.

You can check here https://github.com/tsugliani/freebox-revolution-monitoring and see iy you can use it.

Regards

**Comment by rhaamo** [comment]
Perfect thanks !
