### ISSUE TITLE
Datasource named freebox was not found

### ISSUE THREAD

**Issue by YannickPatois** [tuxtof/freebox-monitoring#3]
Hi,

I installed and started the program as suggested (on debian 8.7), but when I connect to http://localhost:3000/dashboard/file/freebox-grafana.json?refresh=1m&orgId=1, I get empty graphs with a red corner that develop in "Datasource named freebox was not found" on mouseover.

Had a look in the different containers, didnt found anything useful (but dunno where to look).

Any help welcome.

Thanks.

Yannick

**Comment by tuxtof** [comment]
Hi,

can you send me the output of  `docker-compose up` from a clean docker environment

**Comment by YannickPatois** [comment]
Hi,

Thanks for your prompt answer.

So I did:
git clone https://github.com/tuxtof/freebox-monitoring.git
cd freebox-monitoring/
$ docker-compose up
[output.txt](https://github.com/tuxtof/freebox-monitoring/files/987822/output.txt)

Any suggestion?

Thanks.

Yannick

**Comment by tuxtof** [comment]
Hi Yannick,

can you make the following action from your folder freebox-monitoring/ 

`docker-compose rm`
`docker rmi freeboxmonitoring_grafana freeboxmonitoring_telegraf`

relaunch `docker-compose up` and send me the output 
i want see the output during the building of container

Regards

**Comment by YannickPatois** [comment]
Hi,

Sorry, here it is (yes, I dont know Docker well enough yet).
[output2.txt](https://github.com/tuxtof/freebox-monitoring/files/987993/output2.txt)

Regards,
Yannick

**Comment by tuxtof** [comment]
OK understood,
grafana don't have enough time to start before i send the API call to create the data source
i increase the sleep time before launching the API call

can you retry with the last master branch

Reagrds

**Comment by YannickPatois** [comment]
Hi,

Many thanks, it works now :-)

Regards, Yannick

(en fait, je suis sûr qu'on aurait pu causer français, on se serait compris ;-)
